# -------------------------------------------------------------------------
# Application Configurations
# -------------------------------------------------------------------------
spring:
  boot:
    admin:
      discovery:
        management:
          context-path: ${management.context-path}